using Progress.Lang.*.
block-level on error undo, throw.
class ibs.th.bge.egais.ExtFormF1Value:
  define property BottlingDate as character no-undo
    get.
    set.
  define property CliRegIdOrigCli as character no-undo
    get.
    set.
  define property CliEgaisTypeOrigCli as character no-undo
    get.
    set.
  define property INNOrigCli as character no-undo
    get.
    set.
  define property KPPOrigCli as character no-undo
    get.
    set.
  define property FullNameOrigCli as character no-undo
    get.
    set.
  define property CountryOrigCli as character no-undo
    get.
    set.
  define property RegionOrigCli as character no-undo
    get.
    set.
  define property DescrOrigCli as character no-undo
    get.
    set.
  define property FormF1Code as character no-undo
    get.
    set.
  define property AlcCode as character no-undo
    get.
    set.
end class.
